export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_EMPTY_ITEM = 'CART_EMPTY_ITEM';
export const CART_ADD_INCREMENT = 'CART_ADD_INCREMENT';
export const CART_ADD_DECREMENT = 'CART_ADD_DECREMENT';
